variables:
  MAVEN_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository
    - target

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests -DskipITs

unit_test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify -DskipITs
  after_script:
    - |
      echo "Test Coverage Total: $(cat $CI_PROJECT_DIR/target/site/jacoco/index.html | grep -oP 'Total.*?\K([0-9]{1,3})%')"
  artifacts:
    reports:
      junit:
        - '**/target/surefire-reports/TEST-*.xml'

integration_test:
  stage: test
  allow_failure: true  # systems they rely on may not be available
  when: manual
  script:
    - mvn $MAVEN_CLI_OPTS verify -DskipTests
  artifacts:
    reports:
        junit:
        - '**/target/failsafe-reports/TEST-*.xml'

deploy:
  stage: deploy
  only:
    refs:
      - $CI_DEFAULT_BRANCH
      - /^release/.*$/
  script:
    - mvn $MAVEN_CLI_OPTS -s $CI_PROJECT_DIR/.m2/settings.xml source:jar deploy -DskipTests -DskipITs

manual deploy:
  extends: deploy
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^hotfix\/.*$/
  when: manual
  before_script:
    - |
      if [ "$CI_COMMIT_REF_NAME" != "trunk" ]  && ! [[ $CI_COMMIT_REF_NAME =~ release\/.* ]]; then
        mvn $MAVEN_CLI_OPTS versions:set -DgenerateBackupPoms=false -DnewVersion=${CI_COMMIT_REF_SLUG}-SNAPSHOT
      fi

release:
  stage: release
  only:
    - $CI_DEFAULT_BRANCH
    - /^release/.*$/
  when: manual
  script:
    - git checkout -B $CI_COMMIT_BRANCH
    - mvn $MAVEN_CLI_OPTS -s $CI_PROJECT_DIR/.m2/settings.xml release:prepare release:perform -DskipITs
