variables:
  MAVEN_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository
    - target

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: maven:3.6.3-jdk-11

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests -DskipITs

unit_test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify -DskipITs
  after_script:
    - |
      echo "Test Coverage Total: $(cat $CI_PROJECT_DIR/target/site/jacoco/index.html | grep -oP 'Total.*?\K([0-9]{1,3})%')"

integration_test:
  stage: test
  allow_failure: true  # systems they rely on may not be available
  when: manual
  script:
    - mvn $MAVEN_CLI_OPTS verify -DskipTests

deploy:
  stage: deploy
  only:
    - /^release/.*$/
    - /^master$/
  script:
    - mvn $MAVEN_CLI_OPTS -s $CI_PROJECT_DIR/.m2/settings.xml deploy -DskipTests -DskipITs

manual deploy:
  extends: deploy
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^hotfix\/.*$/
  when: manual
  before_script:
    - |
      if [ "$CI_COMMIT_REF_NAME" != "master" ] && ! [[ $CI_COMMIT_REF_NAME =~ release\/.* ]]; then
        mvn $MAVEN_CLI_OPTS versions:set -DgenerateBackupPoms=false -DnewVersion=${CI_COMMIT_REF_SLUG}-SNAPSHOT
      fi
